In [8]:
# importing libraries
import pandas as pd
import numpy as np

In [2]:
# importing datasets
patients = pd.read_csv('D:\python\pandas datasets\patients.csv')
treatments = pd.read_csv(r'D:\python\pandas datasets\treatments.csv')
treatments_cut = pd.read_csv(r'D:\python\pandas datasets\treatments_cut.csv')
adverse_reactions = pd.read_csv(r'D:\python\pandas datasets\adverse_reactions.csv')

In [3]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [18]:
treatments.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [19]:
treatments_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [21]:
adverse_reactions.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

In [23]:
# exporting data for manual assesment

with pd.ExcelWriter('clinical_trials.xlsx') as writer:
    patients.to_excel(writer, sheet_name='patients', index=False)
    treatments.to_excel(writer, sheet_name='treatments', index=False)
    treatments_cut.to_excel(writer, sheet_name='treatment_cut', index=False)
    adverse_reactions.to_excel(writer, sheet_name='adverse_reactions', index=False)

In [5]:
# copying data
patients_df = patients.copy()
treatments_df = treatments.copy()
treatments_cut_df = treatments_cut.copy()
adverse_reactions_df = adverse_reactions.copy()

### 2. Column descriptions

#### **Table** -> `patients`:

- `patient_id`: the unique identifier for each patient in the Master Patient Index (i.e. patient database) of the pharmaceutical company that is producing Auralin
- `assigned_sex`: the assigned sex of each patient at birth (male or female)
- `given_name`: the given name (i.e. first name) of each patient
- `surname`: the surname (i.e. last name) of each patient
- `address`: the main address for each patient
- `city`: the corresponding city for the main address of each patient
- `state`: the corresponding state for the main address of each patient
- `zip_code`: the corresponding zip code for the main address of each patient
- `country`: the corresponding country for the main address of each patient (all United states for this clinical trial)
- `contact`: phone number and email information for each patient
- `birthdate`: the date of birth of each patient (month/day/year). The inclusion criteria for this clinical trial is age >= 18 (there is no maximum age because diabetes is a growing problem among the elderly population)
- `weight`: the weight of each patient in pounds (lbs)
- `height`: the height of each patient in inches (in)
- `bmi`: the Body Mass Index (BMI) of each patient. BMI is a simple calculation using a person's height and weight. The formula is BMI = kg/m2 where kg is a person's weight in kilograms and m2 is their height in metres squared. A BMI of 25.0 or more is overweight, while the healthy range is 18.5 to 24.9. The inclusion criteria for this clinical trial is 16 >= BMI >= 38.

#### **Table** -> `adverse_reactions`

- `given_name`: the given name of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)
- `surname`: the surname of each patient in the Master Patient Index that took part in the clinical trial and had an adverse reaction (includes both patients treated Auralin and Novodra)
- `adverse_reaction`: the adverse reaction reported by the patient

### 3. Additional information

Additional useful information:

- Insulin resistance varies person to person, which is why both starting median daily dose and ending median daily dose are required, i.e., to calculate change in dose.
- It is important to test drugs and medical products in the people they are meant to help. People of different age, race, sex, and ethnic group must be included in clinical trials. This diversity is reflected in the patients table.

### Issues with the dataset

1. Dirty Data

  Table - `Patients`

    - patient_id = 9 has misspelled name 'Dsvid' instead of David `accuracy`
    - state col sometimes contain full name and some times abbrivietation `consistency`
    - zip code col has entries with 4 digit `validity`
    - data missing for 12 patients in address,city,	state,zip_code	,country,	contact `completion`
    - incorrect data type assigned to sex, zip code, birthdate `validity`
    - duplicate entries by the name of John Doe `accuracy`
    - one patient has weight = 48 pounds `accuracy`
    - one patient has height = 27 inches `accuracy`
    - rename given_name , surname, assigned_sex to first_name, last_name and sex in patients table 'consistency'


  Table - `Treatments` & `Treatments_cut`

    - given_name and surname col is is all lower case `consistency`
    - remove u from Auralin and Novadra cols `validity`
    - '-' in novadra and Auralin col treated as nan `validity`
    - missing values in hba1c_change col `completion`
    - in hba1c_change 9 instead of 4 `accuracy`
    -  rename given_name , surname to first_name and last_name in treatments table 'consistency'

2. Messy Data

  Table - `Patients`

    - contact col contains both phone and email

  Table - `Treatments` & `Treatments_cut`

    - Auralin and Novadra col should be split into 2 cols start and end dose
    - merge both the tables

  Table - `Adverse_reactions`

    - This table should not exist independently

## Define
- fill the missing values in patients table with no data
- filled the missing value of hba1c change by subtracting hba1c_end from hba1c_start
- using regex created a function to seperate the phone numbers and email
- dropped contacts column from the patients
- concatinated the treatments and treatments_cut
- dropped treatments_cut
- merged adverse_reactions with treatments
- changed xipcode entries to 4 digit
- changed incorrect data type assigned to sex, zip code, birthdate
- removed u from aurlin and novodra
- '-' in novadra and Auralin col treated as nan
- changed the name from 'Dsvid' to 'David'
- changed the patient weight = 48 pounds to 107 using the given bmi
- changed the patient height = 27 inches to 71.96 using the given bmi
- state col sometimes contain full name and some times abbreviations
- changed given name and surname to capitalized format in patients table
- changed given name and surname to capitalized format in treatments table
- renamed given_name , surname, assigned_sex to first_name, last_name and sex in patients table
-  renamed given_name , surname to first_name and last_name in treatments table

In [24]:
# code
patients_df['zip_code']= patients_df['zip_code'].fillna('No Data')

In [26]:
patients_df = patients_df.fillna('No Data', inplace = True)

In [27]:
#test
patients_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    str
 2   given_name    503 non-null    str
 3   surname       503 non-null    str
 4   address       503 non-null    str
 5   city          503 non-null    str
 6   state         503 non-null    str
 7   zip_code      503 non-null    object
 8   country       503 non-null    str
 9   contact       503 non-null    str
 10  birthdate     503 non-null    str
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(2), int64(2), object(1), str(9)
memory usage: 108.0+ KB

In [33]:
# code 
treatments_df['hba1c_change'] = treatments_df['hba1c_start'] - treatments_df['hba1c_end']

In [35]:
treatments_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    str
 1   surname       280 non-null    str
 2   auralin       280 non-null    str
 3   novodra       280 non-null    str
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  280 non-null    float64
dtypes: float64(3), str(4)
memory usage: 21.8 KB

In [51]:
# code
email_pat = r'([A-Za-z][A-Za-z0-9._-]*@[A-Za-z0-9-]+(?:\.[A-Za-z]+)+)'

# Email
patients_df['email'] = patients_df['contact'].str.extract(email_pat, expand=False)

# Phone: remove the email from the string, keep only digits, take the last 10
patients_df['phone'] = (
    patients_df.apply(lambda r: r['contact'].replace(r['email'], '') if pd.notna(r['email']) else None, axis=1)
    .str.replace(r'\D', '', regex=True)
    .str[-10:]
)

In [127]:
patients_df = patients_df.drop(columns= 'contact')

In [62]:

patients_df['email'] = patients_df['email'].fillna('No Data')

In [65]:
patients_df['phone'] = patients_df['phone'].fillna('No Data')

In [69]:
treatments_df

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
275,albina,zetticci,45u - 51u,-,7.93,7.73,0.20
276,john,teichelmann,-,49u - 49u,7.90,7.58,0.32
277,mathea,lillebø,23u - 36u,-,9.04,8.67,0.37
278,vallie,prince,31u - 38u,-,7.64,7.28,0.36
279,samúel,guðbrandsson,53u - 56u,-,8.00,7.64,0.36

In [78]:
treatments_df= pd.concat([treatments, treatments_cut], ignore_index=True)

In [80]:
treatments_df['hba1c_change'] = treatments_df['hba1c_start'] - treatments_df['hba1c_end']

In [92]:
treatments_df = treatments_df.melt(id_vars=['given_name', 'surname' ,'hba1c_start', 'hba1c_end','hba1c_change'],var_name='type',value_name='dosage_range')

In [94]:
treatments_df = treatments_df[treatments_df['dosage_range'] != '-']

In [96]:
treatments_df['dosage_start'] = treatments_df['dosage_range'].str.split('-').str.get(0)
treatments_df['dosage_end'] = treatments_df['dosage_range'].str.split('-').str.get(1)

In [101]:
treatments_df =treatments_df.drop(columns ='dosage_range')

In [107]:
treatments_df['dosage_start'] =treatments_df['dosage_start'].str.replace('u', '')
treatments_df['dosage_end'] =treatments_df['dosage_end'].str.replace('u', '')

In [112]:
treatments_df = pd.merge(treatments_df, adverse_reactions_df, how =  'left', on = ['given_name', 'surname'])

In [115]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,asia,woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
344,christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
345,maret,sultygov,7.67,7.30,0.37,novodra,26,23,NaN
346,lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
347,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
348,berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [124]:
patients_df['zip_code'] = (
    pd.to_numeric(patients_df['zip_code'], errors='coerce')
    .astype('Int64')
    .astype('string')
    .str.zfill(5)
)

In [134]:
patients_df['zip_code'] = patients_df['zip_code'].fillna('No Data')

In [137]:
patients_df['zip_code'] =patients_df['zip_code'].astype(str)

In [138]:
patients_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    str
 2   given_name    503 non-null    str
 3   surname       503 non-null    str
 4   address       503 non-null    str
 5   city          503 non-null    str
 6   state         503 non-null    str
 7   zip_code      503 non-null    str
 8   country       503 non-null    str
 9   birthdate     503 non-null    str
 10  weight        503 non-null    float64
 11  height        503 non-null    int64
 12  bmi           503 non-null    float64
 13  email         503 non-null    str
 14  phone         503 non-null    str
dtypes: float64(2), int64(2), str(11)
memory usage: 113.0 KB

In [ ]:
treatments_df.to_csv('treatments_cleaned_partial.csv', index=False)

In [35]:
patients_df.to_csv('patients_cleaned_partial.csv', index=False)

NameError: name 'patients_df' is not defined

In [ ]:
treatments_df1 = pd.read_csv(r'D:\python\pandas datasets\treatments_cleaned_partial.csv')

In [105]:
patients_df1 = pd.read_csv('D:\python\pandas datasets\patients_cleaned_partial.csv')

In [106]:
patients_df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    str
 2   given_name    503 non-null    str
 3   surname       503 non-null    str
 4   address       503 non-null    str
 5   city          503 non-null    str
 6   state         503 non-null    str
 7   zip_code      503 non-null    str
 8   country       503 non-null    str
 9   birthdate     503 non-null    str
 10  weight        503 non-null    float64
 11  height        503 non-null    int64
 12  bmi           503 non-null    float64
 13  email         503 non-null    str
 14  phone         503 non-null    str
dtypes: float64(2), int64(2), str(11)
memory usage: 113.0 KB

In [107]:
patients_df1['birthdate'] = pd.to_datetime(patients_df1['birthdate'])

In [108]:
patients_df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    str
 2   given_name    503 non-null    str
 3   surname       503 non-null    str
 4   address       503 non-null    str
 5   city          503 non-null    str
 6   state         503 non-null    str
 7   zip_code      503 non-null    str
 8   country       503 non-null    str
 9   birthdate     503 non-null    datetime64[us]
 10  weight        503 non-null    float64
 11  height        503 non-null    int64
 12  bmi           503 non-null    float64
 13  email         503 non-null    str
 14  phone         503 non-null    str
dtypes: datetime64[us](1), float64(2), int64(2), str(10)
memory usage: 108.7 KB

In [109]:
# Code
patients_df1.loc[patients_df1["given_name"] == "Dsvid", "given_name"] = "David"

In [110]:
# test
patients_df1[patients_df1['patient_id'] == 9]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email,phone
8,9,male,David,Gustafsson,1790 Nutter Street,Kansas City,MO,64105,United States,1937-03-06,163.9,66,26.5,DavidGustafsson@armyspy.com,8162659578

In [111]:
# code
patients_df1.loc[patients_df1['weight'] == 48.80, 'weight'] = 107.5

In [112]:
# test
patients_df1[patients_df1['weight'] == 107.5]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email,phone
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691,United States,1938-11-26,107.5,63,19.1,CamillaZaitseva@superrito.com,3302022145

In [113]:
# test
patients_df1.describe()

,patient_id,birthdate,weight,height,bmi
count,503.000000,503,503.000000,503.000000,503.000000
mean,252.000000,1959-02-03 15:33:16.819086,173.551690,66.634195,27.483897
min,1.000000,1921-11-06 00:00:00,102.100000,27.000000,17.100000
25%,126.500000,1938-04-13 00:00:00,149.300000,63.000000,23.300000
50%,252.000000,1959-04-10 00:00:00,175.300000,67.000000,27.200000
75%,377.500000,1978-04-16 00:00:00,199.500000,70.000000,31.750000
max,503.000000,1999-07-03 00:00:00,255.900000,79.000000,37.700000
std,145.347859,NaN,33.586425,4.411297,5.276438

In [114]:
# code
patients_df1.loc[patients_df1['height'] == 27, 'height'] = 72

In [116]:
# test
patients_df1.describe()

,patient_id,birthdate,weight,height,bmi
count,503.000000,503,503.000000,503.000000,503.000000
mean,252.000000,1959-02-03 15:33:16.819086,173.551690,66.723658,27.483897
min,1.000000,1921-11-06 00:00:00,102.100000,59.000000,17.100000
25%,126.500000,1938-04-13 00:00:00,149.300000,63.000000,23.300000
50%,252.000000,1959-04-10 00:00:00,175.300000,67.000000,27.200000
75%,377.500000,1978-04-16 00:00:00,199.500000,70.000000,31.750000
max,503.000000,1999-07-03 00:00:00,255.900000,79.000000,37.700000
std,145.347859,NaN,33.586425,4.047179,5.276438

In [91]:
# code 
treatments_df1['hba1c_change'].sort_values(ascending = False)

90     0.54
216    0.54
23     0.54
266    0.53
259    0.52
       ...
99     0.27
65     0.27
118    0.26
209    0.24
132    0.20
Name: hba1c_change, Length: 349, dtype: float64

In [117]:
patients_df1[['state']]

          state
0    California
1      Illinois
2      Nebraska
3            NJ
4            AL
..          ...
498          ME
499          AZ
500          MO
501          WA
502    Nebraska

[503 rows x 1 columns]

In [118]:
# code
state_mapping = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    }

In [119]:
patients_df1['state'] = patients_df1['state'].str.strip().str.upper().replace(state_mapping).str.title()

In [120]:
# test
patients_df1[['state', 'given_name']]

          state given_name
0    California        Zoe
1      Illinois     Pamela
2      Nebraska        Jae
3    New Jersey       Liêm
4       Alabama        Tim
..          ...        ...
498       Maine    Mustafa
499     Arizona      Ruman
500    Missouri      Jinke
501          Wa    Chidalu
502    Nebraska        Pat

[503 rows x 2 columns]

In [121]:
# code
patients_df1['given_name'] = patients_df1['given_name'].str.capitalize()

In [123]:
# test
patients_df1

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email,phone
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390,United States,1976-07-10,121.7,66,19.6,ZoeWellish@superrito.com,9517199170
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812,United States,1967-04-03,118.8,66,19.2,PamelaSHill@cuvox.de,2175693204
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467,United States,1980-02-19,177.8,71,24.8,JaeMDebord@gustr.com,4023636804
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,New Jersey,07095,United States,1951-07-26,220.9,70,31.7,PhanBaLiem@jourrapide.com,7326368246
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,Alabama,36303,United States,1928-02-18,192.3,72,26.1,TimNeudorf@cuvox.de,3345157487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,Maine,03852,United States,1959-04-10,181.1,72,24.6,MustafaLindstrom@jourrapide.com,2074770579
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,Arizona,86341,United States,1948-03-26,239.6,70,34.4,RumanBisliev@gustr.com,9282844492
500,501,female,Jinke,de Keizer,649 Nutter Street,Overland Park,Missouri,64110,United States,1971-01-13,171.2,67,26.8,JinkedeKeizer@teleworm.us,8162236007
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,Wa,98109,United States,1952-02-13,176.9,67,27.7,ChidaluOnyekaozulu@jourrapide.com,3604432060
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324,United States,1954-05-03,138.2,71,19.3,PatrickGersten@rhyta.com,4028484923

In [124]:
# code
patients_df1['surname'] = patients_df1['surname'].str.capitalize()

In [125]:
#test
patients_df1.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,email,phone
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390,United States,1976-07-10,121.7,66,19.6,ZoeWellish@superrito.com,9517199170
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812,United States,1967-04-03,118.8,66,19.2,PamelaSHill@cuvox.de,2175693204
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467,United States,1980-02-19,177.8,71,24.8,JaeMDebord@gustr.com,4023636804
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,New Jersey,07095,United States,1951-07-26,220.9,70,31.7,PhanBaLiem@jourrapide.com,7326368246
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,Alabama,36303,United States,1928-02-18,192.3,72,26.1,TimNeudorf@cuvox.de,3345157487

In [147]:
# code
treatments_df1['given_name'] =treatments_df1['given_name'].str.capitalize()

In [148]:
#code
treatments_df1['surname'] =treatments_df1['surname'].str.capitalize()

In [149]:
#test
treatments_df1

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,Veronika,Jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,Skye,Gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,Sophia,Haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,Eddie,Archer,7.89,7.55,0.34,auralin,31,38,NaN
4,Asia,Woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
344,Christopher,Woodward,7.51,7.06,0.45,novodra,55,51,nausea
345,Maret,Sultygov,7.67,7.30,0.37,novodra,26,23,NaN
346,Lixue,Hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
347,Jakob,Jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
348,Berta,Napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [138]:
# code 
patients_df1.rename(columns={'given_name': 'first_name'}, inplace=True)

In [139]:
patients_df1.rename(columns={'surname': 'last_name'}, inplace=True)

In [143]:
patients_df1.rename(columns = {'assigned_sex' : 'sex'}, inplace = True)

In [144]:
# test
patients_df1

,patient_id,sex,first_name,last_name,address,city,state,zip_code,country,birthdate,weight,height,bmi,email,phone
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390,United States,1976-07-10,121.7,66,19.6,ZoeWellish@superrito.com,9517199170
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812,United States,1967-04-03,118.8,66,19.2,PamelaSHill@cuvox.de,2175693204
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467,United States,1980-02-19,177.8,71,24.8,JaeMDebord@gustr.com,4023636804
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,New Jersey,07095,United States,1951-07-26,220.9,70,31.7,PhanBaLiem@jourrapide.com,7326368246
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,Alabama,36303,United States,1928-02-18,192.3,72,26.1,TimNeudorf@cuvox.de,3345157487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,Maine,03852,United States,1959-04-10,181.1,72,24.6,MustafaLindstrom@jourrapide.com,2074770579
499,500,male,Ruman,Bisliev,494 Clarksburg Park Road,Sedona,Arizona,86341,United States,1948-03-26,239.6,70,34.4,RumanBisliev@gustr.com,9282844492
500,501,female,Jinke,De keizer,649 Nutter Street,Overland Park,Missouri,64110,United States,1971-01-13,171.2,67,26.8,JinkedeKeizer@teleworm.us,8162236007
501,502,female,Chidalu,Onyekaozulu,3652 Boone Crockett Lane,Seattle,Wa,98109,United States,1952-02-13,176.9,67,27.7,ChidaluOnyekaozulu@jourrapide.com,3604432060
502,503,male,Pat,Gersten,2778 North Avenue,Burr,Nebraska,68324,United States,1954-05-03,138.2,71,19.3,PatrickGersten@rhyta.com,4028484923

In [150]:
# code
treatments_df1.rename(columns={'given_name': 'first_name'}, inplace=True)

In [151]:
# code
treatments_df1.rename(columns={'surname': 'last_name'}, inplace=True)

In [152]:
treatments_df1

,first_name,last_name,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,Veronika,Jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,Skye,Gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,Sophia,Haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,Eddie,Archer,7.89,7.55,0.34,auralin,31,38,NaN
4,Asia,Woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
344,Christopher,Woodward,7.51,7.06,0.45,novodra,55,51,nausea
345,Maret,Sultygov,7.67,7.30,0.37,novodra,26,23,NaN
346,Lixue,Hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
347,Jakob,Jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
348,Berta,Napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [154]:
# exporting clean files
patients_df1.to_csv('patients_full_cleaned',index = False)
treatments_df1.to_csv('treatments_full_cleaned', index = False)